// AUTO-GENERATED by `scripts/extract-showcase.mjs` from
// `src/HELP.fr.md`. Do not edit by hand — re-run `npm run
// showcase:extract` to refresh.
//
// Seed values for the initial wiring. The extraction script
// overwrites this file with content sourced from HELP.fr.md.

import type { ShowcaseEntry } from './showcase-types';

export const SHOWCASE_DATA: ShowcaseEntry[] = [];

// Lookup helper used by both the showcase page (to render the
// section list in order) and main.ts (to find the snippet matching
// a `?demo=<id>` query parameter).
export function findShowcaseEntry(id: string): ShowcaseEntry | undefined {
  return SHOWCASE_DATA.find((e) => e.id === id);
}

// `playground` is a synthetic entry — no fixed snippet, lets the
// hero iframe start empty so visitors can type their own Markdown.
export const PLAYGROUND_ENTRY: ShowcaseEntry = {
  id: 'playground',
  title: '',
  description: '',
  source: '',
};
